# Generated by Django 3.1.2 on 2020-12-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_features',
            field=models.TextField(null=True),
        ),
    ]
