# Generated by Django 3.1.2 on 2020-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201215_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_small',
            field=models.TextField(null=True),
        ),
    ]
