# Generated by Django 3.1.2 on 2020-12-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201221_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_quantity',
            new_name='quantity',
        ),
    ]
